# Generated by Django 4.1.4 on 2023-01-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todooapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-01-16'),
            preserve_default=False,
        ),
    ]
